[package]
name = "bassiemusic"
id = "nl.plaatsoft.bassiemusic"
version = "2.11.0"

[dependencies]
alerts = "0.1.0"
compat = "0.1.0"
fetch = "0.1.0"
jspecify = { maven = "org.jspecify:jspecify:1.0.0" }

[package.metadata.android]
main_activity = ".activities.MainActivity"
key_alias = ""
keystore_password = "bassiemusic"
key_password = "bassiemusic"
proguard_keep = [
    "public class nl.plaatsoft.bassiemusic.components.MusicPlayer { public <init>(android.content.Context, android.util.AttributeSet); }",
]
