[package]
name = "coinlist"
identifier = "ml.coinlist.android"
version = "1.0.0"

[dependencies]
fetch = { path = "../lib/fetch" }
nullsafe = { path = "../lib/nullsafe" }
ratingalert = { path = "../lib/ratingalert" }
updatealert = { path = "../lib/updatealert" }

[package.metadata.android]
main_activity = ".activities.MainActivity"
key_alias = ""
