[package]
name = "bible"
identifier = "nl.plaatsoft.bible"
version = "1.4.0"

[dependencies]
nullsafe = { path = "../lib/nullsafe" }
ratingalert = { path = "../lib/ratingalert" }

[package.metadata.android]
main_activity = ".activities.MainActivity"
key_alias = ""
