[package]
name = "bible"
id = "nl.plaatsoft.bible"
version = "1.4.0"

[dependencies]
alerts = { path = "../lib/alerts" }
nullsafe = { path = "../lib/nullsafe" }

[package.metadata.android]
main_activity = ".activities.MainActivity"
key_alias = ""
proguard_keep = [
    "public class nl.plaatsoft.bible.views.ChapterView { public ChapterView(android.content.Context, android.util.AttributeSet); }",
    "public class nl.plaatsoft.bible.views.SongView { public SongView(android.content.Context, android.util.AttributeSet); }",
    "public class nl.plaatsoft.bible.views.DrawerLayout { public DrawerLayout(android.content.Context, android.util.AttributeSet); }",
]
