[package]
name = "tweakers"
id = "net.tweakers.android"
version = "1.0.0"

[dependencies]
compat = { path = "../../lib/compat" }
nullsafe = { path = "../../lib/nullsafe" }

[package.metadata.android]
key_alias = ""
