[package]
name = "reacttest"
id = "nl.plaatsoft.reacttest"
version = "0.1.0"

[package.metadata.android]
main_activity = ".activities.MainActivity"

[dependencies]
compat = { path = "../../lib/compat" }
reactdroid = { path = "../../lib/reactdroid" }
