[package]
name = "redsquare"
id = "nl.plaatsoft.redsquare.android"
version = "1.1.0"

[dependencies]
compat = "0.1.0"
fetch = "0.1.0"
jspecify = { maven = "org.jspecify:jspecify:1.0.0" }

[package.metadata.android]
main_activity = ".activities.MainActivity"
key_alias = ""
keystore_password = "redsquare"
key_password = "redsquare"
proguard_keep = [
    "public class nl.plaatsoft.redsquare.android.components.GamePage { public <init>(android.content.Context, android.util.AttributeSet); }",
]
