[package]
name = "rfidviewer"
id = "nl.plaatsoft.rfidviewer"
version = "1.0.0"

[dependencies]
compat = { path = "../../lib/compat" }
jspecify = { maven = "org.jspecify:jspecify:1.0.0" }

[package.metadata.android]
main_activity = ".activities.MainActivity"
key_alias = ""
