[package]
name = "bassietest"
id = "nl.plaatsoft.bassietest"
version = "1.0.0"

[dependencies]
alerts = { path = "../../lib/alerts" }
compat = { path = "../../lib/compat" }
fetch = { path = "../../lib/fetch" }
jspecify = { maven = "org.jspecify:jspecify:1.0.0" }

[package.metadata.android]
main_activity = ".activities.MainActivity"
key_alias = ""
