[package]
name = "rfidviewer"
identifier = "nl.plaatsoft.rfidviewer"
version = "1.0.0"

[dependencies]
nullsafe = { path = "../lib/nullsafe" }

[package.metadata.android]
main_activity = ".activities.MainActivity"
key_alias = ""
