[package]
name = "hackernews"
id = "com.ycombinator.news"
version = "1.0.0"

[dependencies]
compat = { path = "../../lib/compat" }
jspecify = { maven = "org.jspecify:jspecify:1.0.0" }

[package.metadata.android]
key_alias = ""
