[package]
name = "coinlist"
id = "ml.coinlist.android"
version = "1.0.0"

[dependencies]
alerts = "0.1.0"
compat = "0.1.0"
fetch = "0.1.0"
jspecify = { maven = "org.jspecify:jspecify:1.0.0" }

[package.metadata.android]
main_activity = ".activities.MainActivity"
key_alias = ""
