[package]
name = "coinlist"
id = "ml.coinlist.android"
version = "1.0.0"

[dependencies]
alerts = { path = "../../lib/alerts" }
compat = { path = "../../lib/compat" }
fetch = { path = "../../lib/fetch" }
nullsafe = { path = "../../lib/nullsafe" }

[package.metadata.android]
main_activity = ".activities.MainActivity"
key_alias = ""
