[package]
name = "redsquare"
identifier = "nl.plaatsoft.redsquare.android"
version = "1.1.0"

[dependencies]
fetch = { path = "../lib/fetch" }
nullsafe = { path = "../lib/nullsafe" }

[package.metadata.android]
main_activity = ".activities.MainActivity"
key_alias = ""
keystore_password = "redsquare"
key_password = "redsquare"
