[package]
name = "bassiemusic"
identifier = "nl.plaatsoft.bassiemusic"
version = "3.0.0"

[package.metadata.android]
main_activity = ".activities.MainActivity"
key_alias = ""
keystore_password = "bassiemusic"
key_password = "bassiemusic"
