name: check

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-format@21
        run: |
          wget -qO /usr/local/bin/clang-format https://github.com/cpp-linter/clang-tools-static-binaries/releases/latest/download/clang-format-21_linux-amd64
          chmod a+x /usr/local/bin/clang-format
          clang-format --version
      - name: Install bob
        run: cargo install --git https://github.com/bplaat/crates.git bob
      - run: ./meta.sh check
